### ISSUE TITLE
when compile and start in development mode get a error about deprecated minimatch 

### ISSUE THREAD

**Issue by GITleonine1989** [kucharzyk/vuejs-java-starter#4]
[ERROR]:npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by kucharzyk** [comment]
Hi,
This waring is caused by old minimatch package used.

There are two options:
- Try to add explicit minimatch version 3.0.2 to package.json but if there was breaking api chanes it could be bad solution.
- Better solution is to upgrade all dependencies to newest versions. It should fix this issue but I have no longer maintenant this project and this will require some work because of api changes. You can try this at your own

**Comment by GITleonine1989** [comment]
got it,tkx
